CREATE TABLE LIVRO (ID BIGINT NOT NULL, DESCRICAO VARCHAR(255), EDITORA VARCHAR(255), ILUSTRACOES SMALLINT DEFAULT 0, ISBN VARCHAR(255), NRODEPAGINAS INTEGER, PRECO FLOAT, TITULO VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE PESSOA (ID BIGINT NOT NULL, CPF VARCHAR(255), PRIMEIRONOME VARCHAR(255), ULTIMONOME VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
